language: swift

os: osx
osx_image: xcode11.1

xcode_project: SessionManager.xcodeproj
xcode_scheme: SessionManager

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version
- xcrun instruments -w 'iPhone 8' || sleep 15

branches:
  only:
  - master
  - fix/travis
  
script:
- set -o -pipefail
- xcodebuild clean build -project "$TRAVIS_XCODE_PROJECT"  -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "name=iPhone 8" -enableCodeCoverage NO | xcpretty

