language: swift
osx_image: xcode10.1

cache: bundler

matrix:
include:
- name: iOS | Swift 4.2
env: LANE=test_ci SCHEME=SessionManager SWIFT_VERSION=4.2
- name: iOS | Swift 4.0
env: LANE=test_ci SCHEME=SessionManager SWIFT_VERSION=4.0
